//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalWSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int GenderID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int PassportID { get; set; }
        public int SNILSID { get; set; }
        public int MedicalCardID { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual MedicalCard MedicalCard { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual SNIL SNIL { get; set; }
    }
}
